import type { Metadata } from "next";
import { Itim } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "../context/AuthContext";


const itins = Itim({
  weight: "400",
  variable: "--font-itim",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${itins.variable} antialiased`}>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
